name:                appTemplate
version:             0.1.1
license:             AllRightsReserved
author:              "Boris Tschochner"
maintainer:          "tschochner@hornetsecurity.com"
copyright:           "Hornetsecurity GmbH"

extra-source-files:
- README.md
- ChangeLog.md

description:         See README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -fno-warn-orphans

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveDataTypeable
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- TemplateHaskell
- LambdaCase
- MonoLocalBinds
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances

dependencies:
- async >= 2.2.1 && < 2.3
- base >= 4.7 && < 5
- bytestring >= 0.10.8.2 && < 0.10.11
- case-insensitive >= 1.2.0.11 && < 1.2.2
- cmdargs >= 0.10.20 && < 0.11
- co-log >= 0.4.0.1 && < 0.4.1
- containers >= 0.6.2.1 && < 0.6.3
- fast-logger >= 2.4.13 && < 3.1
- formatting >= 6.3.7 && < 6.4
- hedis >= 0.10.10 && < 0.13
- ini >= 0.3.6 && < 0.5
- lifted-async >= 0.10.1.2 && < 0.10.2
- monad-control >= 1.0.2.3 && < 1.0.3
- network >= 2.8.0.0 && < 3.1.2
- mtl >= 2.2.2 && < 2.3
- o-clock
- streamly >= 0.5.2 && < 0.8
- safe-exceptions >= 0.1.7.0 && < 0.1.8
- stm >= 2.5.0.0 && < 2.5.1
- stm-chans >= 3.0.0.4 && < 3.0.1
- text >= 1.2.3.1 && < 1.2.5
- time >= 1.8.0.2 && < 1.10
- transformers
- unix >= 2.7.2.2 && < 2.7.3
- unordered-containers >= 0.2.9.0 && < 0.2.11

library:
  source-dirs: src
executables:
  appTemplate:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # do not run parallel garbage collection
    - -with-rtsopts=-qg
    dependencies:
    - appTemplate
tests:
  appTemplate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - appTemplate
    - hspec >= 1.8
    - hspec-expectations-lifted >= 0.10.0 && < 0.11
    - process >= 1.6.3.0 && < 1.6.10
    - silently >= 1.2.5 && < 1.3
  hlint:
    main:                Hlint.hs
    source-dirs:         test/hlint
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hlint >= 2.1.11
