name:                appTemplate
version:             0.1.1
license:             AllRightsReserved
author:              "Boris Tschochner"
maintainer:          "tschochner@hornetsecurity.com"
copyright:           "Hornetsecurity GmbH"

extra-source-files:
- README.md
- ChangeLog.md

description:         See README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveDataTypeable
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- TemplateHaskell
- LambdaCase
- MonoLocalBinds
- MultiParamTypeClasses
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeOperators
- UndecidableInstances

library:
  source-dirs: src
  dependencies:
  - async >= 2.2.1 && < 2.3
  - base >= 4.7 && < 5
  - bytestring >= 0.10.8.2 && < 0.10.9
  - case-insensitive >= 1.2.0.11 && < 1.2.1
  - cmdargs >= 0.10.20 && < 0.11
  - fast-logger >= 2.4.13 && < 2.5
  - formatting >= 6.3.7 && < 6.4
  - hedis >= 0.10.10 && < 0.11
  - ini >= 0.3.6 && < 0.4
  - monad-control >= 1.0.2.3 && < 1.0.3
  - network >= 2.8.0.0 && < 2.8.1
  - mtl >= 2.2.2 && < 2.3
  - o-clock
  - safe-exceptions >= 0.1.7.0 && < 0.1.8
  - stm >= 2.5.0.0 && < 2.5.1
  - text >= 1.2.3.1 && < 1.2.4
  - time >= 1.8.0.2 && < 1.8.1
  - unix >= 2.7.2.2 && < 2.7.3
  - unordered-containers >= 0.2.9.0 && < 0.2.10
executables:
  appTemplate:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # do not run parallel garbage collection
    - -with-rtsopts=-qg
    dependencies:
    - appTemplate
    - base >= 4.7 && < 5
    - formatting >= 6.3.7 && < 6.4
    - ini >= 0.3.6 && < 0.4
    - monad-control >= 1.0.2.3 && < 1.0.3
    - mtl >= 2.2.2 && < 2.3
    - safe-exceptions >= 0.1.7.0 && < 0.1.8
    - text >= 1.2.3.1 && < 1.2.4
tests:
  appTemplate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - appTemplate
    - async >= 2.2.1 && < 2.3
    - base >= 4.7 && < 5
    - bytestring >= 0.10.8.2 && < 0.10.9
    - hedis >= 0.10.10 && < 0.11
    - hspec >= 1.8
    - ini >= 0.3.6 && < 0.4
    - monad-control >= 1.0.2.3 && < 1.0.3
    - mtl >= 2.2.2 && < 2.3
    - safe-exceptions >= 0.1.7.0 && < 0.1.8
    - silently >= 1.2.5 && < 1.3
    - text >= 1.2.3.1 && < 1.2.4
    - unix >= 2.7.2.2 && < 2.7.3
    - unordered-containers >= 0.2.9.0 && < 0.2.10
  hlint:
    main:                Hlint.hs
    source-dirs:         test/hlint
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - hlint >= 2.1.11
