name:                appTemplate
version:             0.1.0.0
license:             AllRightsReserved
author:              "Boris Tschochner"
maintainer:          "tschochner@hornetsecurity.com"
copyright:           "Hornetsecurity GmbH"

extra-source-files:
- README.md
- ChangeLog.md

description:         See README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- TemplateHaskell
- LambdaCase
- MonoLocalBinds
- MultiParamTypeClasses
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeOperators
- UndecidableInstances

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - async >= 2.2.1 && < 2.3
  - case-insensitive
  - configurator >= 0.3.0.0 && < 0.3.1
  - fast-logger >= 2.4.13 && < 2.5
  - hreader >= 1.1.0 && < 1.2
  - hset >= 2.2.0 && < 2.3
  - mtl >= 2.2.2 && < 2.3
  - optparse-applicative >= 0.14.3.0 && < 1.14.4
  - safe-exceptions >= 0.1.7.0 && < 0.1.8
  - stm >= 2.5.0.0 && < 2.5.1
  - text >= 1.2.3.1 && < 1.2.4
  - transformers >= 0.5.5.0 && < 0.5.6
  - type-fun >= 0.1.1 && < 0.2
  - unix >= 2.7.2.2 && < 2.7.3

executables:
  appTemplate:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # do not run parallel garbage collection
    - -with-rtsopts=-qg
    dependencies:
    - appTemplate
    - hreader >= 1.1.0 && < 1.2
    - hset >= 2.2.0 && < 2.3
    - mtl >= 2.2.2 && < 2.3
    - safe-exceptions >= 0.1.7.0 && < 0.1.8
    - type-fun >= 0.1.1 && < 0.2

tests:
  appTemplate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - appTemplate
    - async >= 2.2.1 && < 2.3
    - bytestring >= 0.10.8.2 && < 0.10.9
    - hreader >= 1.1.0 && < 1.2
    - hset >= 2.2.0 && < 2.3
    - hspec >= 1.8
    - fast-logger >= 2.4.13 && < 2.5
    - mtl >= 2.2.2 && < 2.3
    - silently >= 1.2.5 && < 1.3
    - type-fun >= 0.1.1 && < 0.2
    - unix >= 2.7.2.2 && < 2.7.3
  hlint:
    main:                Hlint.hs
    source-dirs:         test/hlint
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hlint >= 2.1.11
